function [ values ] = constants()
    values = struct('n_features', 14,...
                    'n_classes', 11,...
                    'window_size', 256,...
                    'window_step', 128,...
                    'margin', 3,...
                    'silence_threshold', 0.05,...
                    'min_frames_beetween_digits', 10,...
                    'max_silent_frames_in_digit', 5);
                 
end

